package coreWar.graph;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

//import org.knowm.xchart.SwingWrapper;
import org.knowm.xchart.XYChart;
import org.knowm.xchart.QuickChart;
import org.knowm.xchart.BitmapEncoder;
import org.knowm.xchart.BitmapEncoder.BitmapFormat;

import coreWar.trainingManager.TrainingImporter;

public class GraphVisualisation {
    public static void main(String[] args) throws IOException {
        List<List<Integer>> scores = TrainingImporter.importScores();
        System.out.println(scores);
        List<Integer> xData = new ArrayList<Integer>();
        List<Integer> yData = new ArrayList<Integer>();
        for (int i = 0; i < scores.size(); i++) {
            xData.add(i);
            yData.add(scores.get(i).get(0));
        }
        System.out.println(scores.size());

        // Create Chart
        XYChart chart = QuickChart.getChart("Evolution of Challenger's scores generated by G.A. for CoreWar", "Generation", "Scores", "Challenger's scores by generation",xData, yData);

        // Show it
        //new SwingWrapper(chart).displayChart();

        // Save it
        BitmapEncoder.saveBitmapWithDPI(chart, String.format("./graphOfScoreFor%dGen", scores.size()), BitmapFormat.PNG, 300);
    }
}
